name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        source .venv/bin/activate
        # Install ANTLR runtime first to ensure correct version
        uv pip install antlr4-python3-runtime==4.9.3
        uv pip install -e ".[dev]"
    - name: Set up ANTLR
      run: |
        source .venv/bin/activate
        cd sequence_rules/dsl
        export CLASSPATH=".:$PWD/antlr-4.9.3-complete.jar:$CLASSPATH"
        rm -f SequenceRule*.py  # Remove any existing generated files
        java -jar antlr-4.9.3-complete.jar -Dlanguage=Python3 -visitor SequenceRule.g4
        cd ../..
    - name: Run tests with coverage
      run: |
        source .venv/bin/activate
        pytest tests/ --cov=sequence_rules --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: true 